version: "2"

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - bodyclose
    - gocritic
    - gosec
    - nilerr
    - prealloc
    - gocyclo
    - dupl
    - goconst
    - unconvert
  disable:
    - exhaustruct
    - varnamelen
    - wrapcheck

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 200
    goconst:
      min-len: 3
      min-occurrences: 3
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: false
        - name: var-naming
          disabled: false
        - name: package-comments
          disabled: false
    gosec:
      excludes:
        - G104
        - G304

  exclusions:
    presets: []
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - goconst
          - govet
      - path: internal/transport/http/
        linters:
          - dupl
      - path: (_test\.go|migrations/)
        linters:
          - gomnd
      - path: (\.pb\.go|wire_gen\.go)
        linters:
          - lll
      - path: internal/repository/post\.go
        linters:
          - gocyclo

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
