version: 2

# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Essential linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Style
    - misspell
    - revive

    # Bug detection
    - bodyclose
    - gocritic
    - gosec
    - nilerr

    # Performance
    - prealloc

    # Code quality
    - gocyclo
    - dupl
    - goconst
    - unconvert

  disable:
    - exhaustruct
    - varnamelen
    - wrapcheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 200

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

  gosec:
    excludes:
      - G104
      - G304

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst

    - path: internal/transport/http/
      linters:
        - dupl

    - path: (_test\.go|migrations/)
      linters:
        - gomnd

    - path: (\.pb\.go|wire_gen\.go)
      linters:
        - lll

  new: false
