# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Essential linters
    - errcheck # Check for unchecked errors
    - gosimple # Simplify code
    - govet # Vet examines Go source code
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Static analysis checks
    - typecheck # Type checking
    - unused # Check for unused code

    # Style linters
    - gofmt # Check formatting
    - goimports # Check import formatting
    - misspell # Check for misspelled English words
    - revive # Fast, configurable, extensible linter

    # Bug detection
    - bodyclose # Check HTTP response body closed
    - gocritic # Opinionated Go linter
    - gosec # Security checker
    - nilerr # Find code that returns nil even if error is not nil

    # Performance
    - prealloc # Find slice declarations that could be preallocated

    # Code quality
    - gocyclo # Cyclomatic complexity
    - dupl # Code clone detection
    - goconst # Find repeated strings that could be constants
    - unconvert # Remove unnecessary type conversions

  disable:
    - exhaustruct # Too strict for most cases
    - varnamelen # Too opinionated
    - wrapcheck # Too strict for error wrapping

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow # Too strict
      - fieldalignment # Prefer readability over minor memory optimization

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 200

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: package-comments
        disabled: false

  gosec:
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
      - G304 # File path from variable (needed for file operations)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst

    # Exclude dupl from HTTP handlers (common patterns)
    - path: internal/transport/http/
      linters:
        - dupl

    # Ignore magic numbers in tests and migrations
    - path: (_test\.go|migrations/)
      linters:
        - gomnd

    # Ignore long lines in generated code
    - path: (\.pb\.go|wire_gen\.go)
      linters:
        - lll

  # Show only new issues
  new: false
